// Generates the vendor Ed25519 license-signing key pair — run it ONCE, on YOUR OWN trusted computer.
//
//   npm run license:keygen                      -> private key in ~/.sabermarko-vendor-keys/ (outside the repository)
//   npm run license:keygen -- --out D:\keys     -> or any folder you choose, e.g. an encrypted USB drive
//   SBM_KEY_PASSPHRASE=... npm run license:keygen   -> private key additionally encrypted with a passphrase
//
// The PRIVATE key never goes into the repository: the tool refuses any folder inside a git working tree.
// The PUBLIC key is written into src/main/license/public-key.ts (safe to commit) and its fingerprint is printed.
import { generateKeyPairSync } from 'node:crypto';
import { existsSync, mkdirSync, writeFileSync, chmodSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { DEFAULT_KEY_DIR, PUBLIC_KEY_TS, fingerprint, insideGitRepo, parseArgs } from './common.mjs';

const args = parseArgs(process.argv.slice(2));
const dir = resolve(typeof args.out === 'string' ? args.out : DEFAULT_KEY_DIR);
if (insideGitRepo(dir)) {
  console.error(`رفض: المجلد ${dir} داخل مستودع git. المفتاح الخاص يجب أن يبقى خارج أي مستودع.\nRefused: ${dir} is inside a git working tree. Choose a folder outside any repository (--out).`);
  process.exit(2);
}
const privFile = join(dir, 'private.pem');
if (existsSync(privFile) && !args.force) {
  console.error(`A private key already exists at ${privFile}. Use --force to replace it (this invalidates EVERY license issued with the old key).`);
  process.exit(1);
}
mkdirSync(dir, { recursive: true, mode: 0o700 });
const { publicKey, privateKey } = generateKeyPairSync('ed25519');
const passphrase = process.env.SBM_KEY_PASSPHRASE || '';
const privPem = passphrase
  ? privateKey.export({ type: 'pkcs8', format: 'pem', cipher: 'aes-256-cbc', passphrase })
  : privateKey.export({ type: 'pkcs8', format: 'pem' });
writeFileSync(privFile, privPem, { mode: 0o600 });
try { chmodSync(privFile, 0o600); } catch { /* Windows: rely on the profile folder ACL */ }
const pub = publicKey.export({ type: 'spki', format: 'pem' }).toString();
writeFileSync(join(dir, 'public.pem'), pub);
writeFileSync(PUBLIC_KEY_TS, `// Vendor license verification key (PUBLIC — safe to commit). Generated by tools/license/keygen.mjs\n// Fingerprint: ${fingerprint(pub)}\nexport const LICENSE_PUBLIC_KEY = \`${pub.trim()}\`;\n`);
console.log(`Private key : ${privFile}${passphrase ? ' (encrypted with your passphrase)' : ''}`);
console.log(`Public key  : written to ${PUBLIC_KEY_TS}`);
console.log(`Fingerprint : ${fingerprint(pub)}`);
console.log('\nNEXT: back up the private key OFFLINE (two copies). Whoever holds it can issue licenses. Never commit or e-mail it.');
console.log('Then commit src/main/license/public-key.ts and build the release.');
