// Generates the vendor Ed25519 key pair.
// The PRIVATE key stays with the vendor (.vendor-keys/, git-ignored) and is used to issue licenses.
// The PUBLIC key is written into the app source (src/main/license/public-key.ts).
import { generateKeyPairSync } from 'node:crypto';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';

const dir = '.vendor-keys';
if (existsSync(`${dir}/private.pem`) && !process.argv.includes('--force')) {
  console.error('Key already exists. Use --force to replace it (this invalidates every issued license).');
  process.exit(1);
}
mkdirSync(dir, { recursive: true });
const { publicKey, privateKey } = generateKeyPairSync('ed25519');
writeFileSync(`${dir}/private.pem`, privateKey.export({ type: 'pkcs8', format: 'pem' }), { mode: 0o600 });
const pub = publicKey.export({ type: 'spki', format: 'pem' });
writeFileSync(`${dir}/public.pem`, pub);
writeFileSync('src/main/license/public-key.ts', `// Vendor license verification key (public). Generated by tools/license/keygen.mjs\nexport const LICENSE_PUBLIC_KEY = \`${pub.trim()}\`;\n`);
console.log('Key pair generated. Keep .vendor-keys/private.pem safe and OFF the repository.');
