// Vendor license verification key (public). Generated by tools/license/keygen.mjs
export const LICENSE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA0vgaJlNMtX9vtI4B2Z2vH/kMPfgtZ6y5/0YvB1pnVrE=
-----END PUBLIC KEY-----`;
